# 389. Find the Difference


from colorama import Fore as F
import argparse


def BuildArgParser(descr):
	parser = argparse.ArgumentParser(descr)
	parser.add_argument('-s', nargs='?', type=str, help='S string')
	parser.add_argument('-t', nargs='?', type=str, help='T string')
	parser.add_argument('-d', '--description', action='store_true', help='Show description')
	parser.add_argument('-e', '--example', action='store_true', help='Show example')

	return parser 


def make_list(string):
    lst = []
    for el in string:
        lst.append(el)
    return lst

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        lst_s = make_list(s)
        lst_t = make_list(t)
        
        for element in lst_s:
            if element in lst_t:
                lst_t.remove(element)
        
        return lst_t[0]


def main():
	descr = f'''
{F.RED}=========================================================={F.RESET}
{F.GREEN}
	# 389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and 
then add one more letter at a random position.

Return the letter that was added to t
{F.RESET}
{F.RED}=========================================================={F.RESET}
	'''

	example = f'''
Example 1:
	$ python3 l-0389.py -s "abcd" -t "abcde"
	>>> e
	{F.GREEN}Explanation: 'e' is the letter that was added.{F.RESET}

Example 3:
	$ python3 l-0389.py -s "a" -t "aa"
	>>> a

Example 3:

	$ python3 l-0389.py -s "ae" -t"aea"
	>>> a
	'''

	parser = BuildArgParser(descr)
	args = parser.parse_args()


	if args.s and args.t:
		result = Solution().findTheDifference(s=args.s, t=args.t)
		print(result)

	elif args.description:
		print(descr)

	elif args.example:
		print(example)

	else:
		parser.print_help()


if __name__=='__main__':
	main()
